server:
  port: 8000

#spring:

#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/comm
#    username: root
#    password: 1234

mybatis:
  mapper-locations:
    - /mappers/*.xml